### PR TITLE
Remove Component Helper Functions

### PR DESCRIPTION
**Pull request by fcheadle**
This PR addresses the discussion in #17 

I've removed the AddComponent etc. methods and relied on having things added to AllComponents.

### CODE REVIEW

**Review by Chris3606 — COMMENTED** [review]
A couple final thoughts:

a) GameObject from GoRogue performs sanity checks to ensure a component is not added to more than one object simultaneously (see [here](https://github.com/Chris3606/GoRogue/blob/61119579c8c6f9a84b8a8c74cf18bfe274074522/GoRogue/GameFramework/GameObject.cs#L138)); I think for 100% parity with that feature set we could perform the same check in `On_GoRogueComponentAdded` here.

b) The current `On_GoRogueComponentRemoved` handler does not assign `null` to the parent of any `IGameObjectComponents` being used (see [here](https://github.com/Chris3606/GoRogue/blob/61119579c8c6f9a84b8a8c74cf18bfe274074522/GoRogue/GameFramework/GameObject.cs#L145)).  I believe this is necessary to ensure that field gets synced up 100% of the time.

**Comment by fcheadle** [comment]
Added that to the latest version. Due to a mistake while switching branches, I've also pushed the recommended solution for issue #23

**Comment by fcheadle** [comment]
Also includes fix for #25. It was low-hanging fruit

**Review by Chris3606 — APPROVED** [review]
:shipit:

**Pull request merged**
